# Shell variables
# Generated by 'wal'
wallpaper="/home/diego/dotfiles/wallpapers/Wallpapers/dandadan-momo-4k.webp"

# Special
background='#1a0d1e'
foreground='#c5c2c6'
cursor='#c5c2c6'

# Colors
color0='#1a0d1e'
color1='#8C3A90'
color2='#92468B'
color3='#A96196'
color4='#C579B3'
color5='#358B9B'
color6='#39A9AF'
color7='#c5c2c6'
color8='#6d5c70'
color9='#8C3A90'
color10='#92468B'
color11='#A96196'
color12='#C579B3'
color13='#358B9B'
color14='#39A9AF'
color15='#c5c2c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
