--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/diego/dotfiles/wallpapers/Wallpapers/itachi-uchiha-amoled-minimal-art-3840x2160-4k.jpg"

-- Special
background="#0c0505"
foreground="#c2c0c0"
cursor="#c2c0c0"

-- Colors
color0="#0c0505"
color1="#AB1A11"
color2="#A32722"
color3="#D71F16"
color4="#D62116"
color5="#A95E5B"
color6="#9E807E"
color7="#c2c0c0"
color8="#675555"
color9="#AB1A11"
color10="#A32722"
color11="#D71F16"
color12="#D62116"
color13="#A95E5B"
color14="#9E807E"
color15="#c2c0c0"
