# Shell variables
# Generated by 'wal'
wallpaper="/home/diego/dotfiles/wallpapers/Wallpapers/itachi-uchiha-amoled-minimal-art-3840x2160-4k.jpg"

# Special
background='#0c0505'
foreground='#c2c0c0'
cursor='#c2c0c0'

# Colors
color0='#0c0505'
color1='#AB1A11'
color2='#A32722'
color3='#D71F16'
color4='#D62116'
color5='#A95E5B'
color6='#9E807E'
color7='#c2c0c0'
color8='#675555'
color9='#AB1A11'
color10='#A32722'
color11='#D71F16'
color12='#D62116'
color13='#A95E5B'
color14='#9E807E'
color15='#c2c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
