--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/diego/dotfiles/wallpapers/Wallpapers/dandadan-momo-4k.webp"

-- Special
background="#1a0d1e"
foreground="#c5c2c6"
cursor="#c5c2c6"

-- Colors
color0="#1a0d1e"
color1="#8C3A90"
color2="#92468B"
color3="#A96196"
color4="#C579B3"
color5="#358B9B"
color6="#39A9AF"
color7="#c5c2c6"
color8="#6d5c70"
color9="#8C3A90"
color10="#92468B"
color11="#A96196"
color12="#C579B3"
color13="#358B9B"
color14="#39A9AF"
color15="#c5c2c6"
