#!/bin/bash
# autopress-menu (NixOS Wayland ver)
# ydotool funciona en modo directo (sin daemon)

~/.local/bin/autopress

echo
echo -e "\033[1;33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m✅ Proceso completado\033[0m"
echo -e "\033[0;36mPresiona Enter para cerrar...\033[0m"
read -r
